name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Install uv
        run: pip install uv==0.11.2

      - name: Install data_pipeline deps
        working-directory: data_pipeline
        run: uv sync --group dev

      - name: Install model_serving deps
        working-directory: model_serving
        run: uv sync --group dev

      - name: Install drift_monitoring deps
        working-directory: drift_monitoring
        run: uv sync

      - name: Run Linter
        run: |
          flake8 . \
            --exclude=.venv,mlruns,dvc-storage,__pycache__,.pytest_cache,data,logs,models,models_local,.dvc

      - name: Run Tests (data_pipeline)
        working-directory: data_pipeline
        run: uv run pytest tests/

      - name: Run Tests (model_serving)
        working-directory: model_serving
        run: uv run pytest tests/
