stages:
  load:
    cmd: python src/load.py --source_path ${data.source_path} --output_path data/raw.csv
    deps:
      - src/load.py
      - ${data.source_path}
    outs:
      - data/raw.csv:
          cache: false

  process:
    cmd: python src/process.py --input_path data/raw.csv --train_output data/train.csv --prod_output data/prod_sim.csv --year_threshold ${data.train_year_threshold}
    deps:
      - data/raw.csv
      - src/process.py
    outs:
      - data/train.csv
      - data/prod_sim.csv

  train:
    cmd: python src/train.py --data_path data/train.csv --params_path params.yaml
    deps:
      - data/train.csv
      - src/train.py
    params:
      - params.yaml:
          - train
    outs:
      - models/:
          cache: false

  evaluate:
    cmd: python src/evaluate.py --train_data data/train.csv
    deps:
      - src/evaluate.py
      - models/
    metrics:
      - metrics.json:
          cache: false
