stages:
  load:
    cmd: python src/load.py --source_path songs.csv --output_path data/raw.csv
    deps:
      - src/load.py
      - songs.csv
    outs:
      - data/raw.csv

  process:
    cmd: python src/process.py --input_path data/raw.csv --train_output data/train.csv --prod_output data/prod_sim.csv --year_threshold 2010
    deps:
      - src/process.py
      - data/raw.csv
    outs:
      - data/train.csv
      - data/prod_sim.csv

  train:
    cmd: python src/train.py --data_path data/train.csv --params_path params.yaml
    deps:
      - src/train.py
      - data/train.csv
      - params.yaml
    outs:
      - models

  evaluate:
    cmd: python src/evaluate.py --data_path data/prod_sim.csv --model_path models --params_path params.yaml
    deps:
      - src/evaluate.py
      - data/prod_sim.csv
      - models
      - params.yaml
    outs:
      - metrics.json




